name: Daily Court Charge Updater

on:
  schedule:
    - cron: '25 9 * * 1-5'   # Runs at 08:25 UTC, Monday–Friday
  workflow_dispatch:         # Allows manual trigger

jobs:
  fetch-charges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pipenv
        run: pip install pipenv

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pipenv install

      - name: Run fetch_charges.py
        env:
          KEY: ${{ secrets.KEY }}
        run: pipenv run python fetch_charges.py
